<DIV id=footer>
<!-- #INCLUDE FILE="ExtraHTM.txt" -->

<P id=copyright><%=Copyright%></P>

<% '## START - REMOVAL, MODIFICATION OR CIRCUMVENTING (Including Commenting Out) THIS CODE WILL VIOLATE THE Matthew1471 BlogX Proxy LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>

<P id=poweredBy>Powered by <A href="<% If AboutPage = True Then Response.Write SiteURL & "About.asp" Else Response.Write "http://blogX.co.uk/About.asp"%>"><acronym title="Powered By: Matthew1471 BlogXProxy Version V<%=Version%>">Matthew1471's BlogXProxy</acronym></A></P></DIV>
<% '## END - REMOVAL, MODIFICATION OR CIRCUMVENTING (Including Commenting Out) THIS CODE WILL VIOLATE THE Matthew1471 BlogX Proxy LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>

<!-- Generated by Matthew1471 BlogX v.<%=Version%> --></BODY></HTML>
<% Set Records = Nothing
Database.Close
Set Database = Nothing
%>