<!-- #INCLUDE FILE="News.asp" -->
      </tr>

    <tr>
      <td width="100%" bgcolor="#1843C4" height="26">
      <font face="Verdana" size="2" color="#FFFFFF"><b>Top 10 Blogs On <%=Domain%></b></font>
      </td>
    </tr>

    <tr>
      <td width="100%" bgcolor="#FFFFFF" height="97" align="center" style="PADDING-BOTTOM: 5px;"><br>
                  <!--msimagelist--><table border="0" cellpadding="0" cellspacing="0" width="50%">
                  <!-- #INCLUDE FILE="Top10.asp" -->
                  <!--msimagelist--></table><br>                  
                  <center><A title="See The Top Blogs On <%=Domain%>" href="<%=Root%>Ranks.asp">More >></A></center>
      </td>
    </tr>

    <tr>
      <td width="100%" bgcolor="#FFCC00" colspan="2" height="21" align="right" style="PADDING-RIGHT: 5px;">
<% '## START - REMOVAL, MODIFICATION OR CIRCUMVENTING THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>
<small>Powered By <a href="About.asp">Matthew1471's AdminToolKit</a></small>
<% '## END - REMOVAL, MODIFICATION OR CIRCUMVENTING THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>
      </td>
    </tr>
  </table>
  <center><font size="1" face="Verdana"><%=Company%> © Copyright 2003 - 2004<br><A href="<%=Root%>Terms.asp">Terms &amp; Conditions</A> | <A href="<%=Root%>Admin_Default.asp">Owner Login</A></font></center>

<%'--- This means you'll get added to "OtherLinks.txt" in future ---'
If Register = True Then Response.Write "<Img Src=""http://matthew1471.co.uk/Blog/Count.asp"" width=""1"" height=""1"">"
%>
<!-- Generated by Matthew1471 BlogX ToolKit v.<%=Version%> --></Body></Html>