<DIV id=footer>
<!-- #INCLUDE FILE="ExtraHTM.txt" -->

<P id=copyright><%=Copyright%><% If RSS <> 0 Then 
Response.Write " | Subscribe to my <A class=""standardsButton"" href=""" & SiteURL & "RSS/"
If (ReaderPassword <> "") AND Session("Reader") = True Then Response.Write "?" & ReaderPassword
Response.Write """>RSS</A> feed"
End If
%>
<% If MailingList <> 0 Then Response.Write VbCrlf & "<br>Subscribe to my <A class=""standardsButton"" href=""" & SiteURL & "MailingList.asp"">Mailing List</A>"%>.</P>

<% '## START - REMOVAL, MODIFICATION OR CIRCUMVENTING (Including Commenting Out) THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>

<P id=poweredBy>Powered by <A href="<% If AboutPage = True Then Response.Write SiteURL & "About.asp" Else Response.Write "http://blogX.co.uk/About.asp"%>"><acronym title="Powered By: Matthew1471 BlogX Version V<%=Version%>">Matthew1471's edition of BlogX</acronym></A></P></DIV>
<% '## END - REMOVAL, MODIFICATION OR CIRCUMVENTING (Including Commenting Out) THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY MEAN LEGAL ACTION ##' %>

<%'--- This means you'll get added to "OtherLinks.txt" in future ---'
If Register = True Then Response.Write "<Img Src=""http://blogx.co.uk/Count.asp"" width=""1"" height=""1"">"
%>
<!-- Generated by Matthew1471 BlogX v.<%=Version%> --></BODY></HTML>
<% Set Records = Nothing
Database.Close
Set Database = Nothing
%>