<%
' --------------------------------------------------------------------------
'¦Introduction : Page Footer.                                               ¦
'¦Purpose      : Inserts the footer and finishes the page (both the HTML and¦
'¦               clears the objects and also closes the database.)          ¦
'¦Requires     : ExtraHTM.txt, RSS/, Blank.gif, About.asp, Database open.   ¦
'¦Used By      : Most pages.                                                ¦
'---------------------------------------------------------------------------

'*********************************************************************
'** Copyright (C) 2003-09 Matthew Roberts, Chris Anderson
'**
'** This is free software; you can redistribute it and/or
'** modify it under the terms of the GNU General Public License
'** as published by the Free Software Foundation; either version 2
'** of the License, or any later version.
'**
'** All copyright notices regarding Matthew1471's BlogX
'** must remain intact in the scripts and in the outputted HTML
'** The "Powered By" text/logo with the http://www.blogx.co.uk link
'** in the footer of the pages MUST remain visible.
'**
'** This program is distributed in the hope that it will be useful,
'** but WITHOUT ANY WARRANTY; without even the implied warranty of
'** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'** GNU General Public License for more details.
'**********************************************************************

 Response.Write VbCrlf & VbCrlf & "<div id=""footer"">" & VbCrlf
 %><!-- #INCLUDE FILE="ExtraHTM.txt" --><%

 '-- Seperate from the ExtraHTM.txt --'
 Response.Write VbCrlf & VbCrlf

 Response.Write " <p id=""copyright"">" & Copyright

 '-- Link to RSS. --'
 If RSS <> 0 Then 
  Response.Write " | Subscribe to my <a class=""standardsButton"" href=""" & SiteURL & "RSS/"
  If (ReaderPassword <> "") AND Session("Reader") = True Then Response.Write "?" & ReaderPassword
  Response.Write """>RSS</a> feed"
  Response.Write " | Get updates using <a class=""standardsButton"" onclick=""makeSNSRequest('" & SiteURL & "')"" href=""#"">SNS</a>"
 End If

 '-- Link to mailing list. --'
 If (MailingList <> 0) AND (EnableEmail <> False) Then Response.Write VbCrlf & " <br/>Subscribe to my <a class=""standardsButton"" href=""" & SiteURL & "MailingList.asp"">Mailing List</a>"
 
 Response.Write ".</p>" & VbCrlf & VbCrlf

 '## START - REMOVAL, MODIFICATION OR CIRCUMVENTING (including commenting) THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY RESULT IN LEGAL ACTION ##'
  Response.Write " <p id=""poweredBy"">Powered by <a href="""
  If AboutPage = True Then Response.Write SiteURL & "About.asp" Else Response.Write "http://blogX.co.uk/About.asp"
  Response.Write """><acronym title=""Powered By: Matthew1471 BlogX Version V" & Version & """>Matthew1471's edition of BlogX</acronym></a></p></div>" & VbCrlf & VbCrlf
 '## END - REMOVAL, MODIFICATION OR CIRCUMVENTING (including commenting) THIS CODE WILL VIOLATE THE Matthew1471 BlogX LICENSE AGREEMENT & MAY RESULT IN LEGAL ACTION ##'

 '--- This means you'll get added to "OtherLinks.txt" in future ---'
 If Register = True Then Response.Write " <div><img alt=""BlogX.co.uk Beacon"" src=""http://blogx.co.uk/Official/Count.asp"" width=""1"" height=""1""/></div>" & VbCrlf & VbCrlf

 Response.Write " <!-- SNS Code -->" & VbCrlf
 Response.Write " <div><img alt=""Hidden Image For SNS Client"" id=""SNSFirer"" src=""" & SiteURL & "Images/Blank.gif"" width=""1"" height=""1"" style=""display:none;""/></div>" & VbCrlf
 Response.Write " <!-- End Of SNS Code -->" & VbCrlf & VbCrlf

 Response.Write " <!-- Generated by Matthew1471 BlogX v." & Version & " -->" & VbCrlf
 Response.Write " </body>" & VbCrlf
 Response.Write "</html>" & VbCrlf

'-- Clean up. --'
Set Records = Nothing
Database.Close
Set Database = Nothing
%>